# Generated by Django 5.1.3 on 2025-01-22 15:38

import django.core.validators
import store.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default.png', upload_to=store.models.get_profile_path, validators=[django.core.validators.FileExtensionValidator(['png', 'jpg'])]),
        ),
    ]
