# Generated by Django 5.1.3 on 2025-01-22 16:00

import django.core.validators
import store.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default.png', upload_to=store.models.get_profile_path, validators=[django.core.validators.FileExtensionValidator(['png', 'jpg'])]),
        ),
    ]
