# Generated by Django 5.1.3 on 2025-11-07 13:16

import cloudinary_storage.storage
import django.core.validators
import store.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_remove_profile_image_profileuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to=store.models.get_file_path),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to=store.models.get_file_path),
        ),
        migrations.AlterField(
            model_name='profileuser',
            name='image',
            field=models.ImageField(default='default.png', storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to=store.models.get_profile_path, validators=[django.core.validators.FileExtensionValidator(['png', 'jpg'])]),
        ),
    ]
